dependencies:
  - '@fastify/compress'
  - '@fastify/multipart'
  - '@fastify/static'
  - '@nestjs/bullmq'
  - '@nestjs/common'
  - '@nestjs/core'
  - '@nestjs/microservices'
  - '@nestjs/platform-fastify'
  - '@nestjs/swagger'
  - '@qdrant/js-client-rest'
  - bullmq
  - class-transformer
  - class-validator
  - date-fns
  - fastify
  - ioredis
  - joi
  - ollama
  - pino
  - pino-pretty
  - reflect-metadata
  - rxjs
devDependencies:
  - '@changesets/cli'
  - '@eslint/js'
  - '@nestjs/cli'
  - '@nestjs/schematics'
  - '@nestjs/testing'
  - '@types/eslint'
  - '@types/jest'
  - '@types/node'
  - '@types/supertest'
  - depcheck
  - dependency-cruiser
  - dotenv-cli
  - eslint
  - eslint-config-prettier
  - eslint-plugin-prettier
  - eslint-plugin-simple-import-sort
  - eslint-plugin-sonarjs
  - globals
  - husky
  - jest
  - jest-extended
  - jest-junit
  - jiti
  - js-yaml
  - lint-staged
  - npm-check-updates
  - rimraf
  - source-map-support
  - supertest
  - ts-jest
  - ts-loader
  - ts-node
  - ts-unused-exports
  - tsconfig-paths
  - typescript
  - typescript-eslint
peerDependencies: []
internalDependencies:
  - '@ehildt/ckir-bullmq'
  - '@ehildt/ckir-bullmq-logger'
  - '@ehildt/ckir-config-factory'
  - '@ehildt/ckir-helpers'
  - '@ehildt/ckir-ollama'
  - '@ehildt/ckir-qdrant'
  - '@ehildt/ckir-socket-io'
_hash: be12a051ecd9606f4abc3733da93de4c15c5f3f895153437a0477534cb927267
